<?php

namespace App\Config;

use Ppci\Config\RightsPpci;

/**
 * List of all rights required by modules
 */
class Rights extends RightsPpci
{
    protected array $rights = [
        "individuList" => ["lecture"],
        "individuDisplay" => ["lecture"],
        "individuChange" => ["manage"],
        "individuWrite" => ["manage"],
        "individuDelete" => ["manage"],
        "individuGetListEspece" => ["lecture"],
        "pieceDisplay" => ["lecture"],
        "pieceChange" => ["manage"],
        "pieceWrite" => ["manage"],
        "pieceDelete" => ["manage"],
        "pieceList" => ["lecture"],
        "pieceExportCS" => ["manage"],
        "photoDisplay" => ["lecture"],
        "photoChange" => ["manage"],
        "photoWrite" => ["manage"],
        "photoDelete" => ["manage"],
        "photoGetPhoto" => ["lecture"],
        "photoGetThumbnail" => ["lecture"],
        "lecteurList" => ["gestionCompte"],
        "lecteurDisplay" => ["gestionCompte"],
        "lecteurChange" => ["gestionCompte"],
        "lecteurWrite" => ["gestionCompte"],
        "lecteurDelete" => ["gestionCompte"],
        "lecteurListFromExp" => ["lecture"],
        "parametres" => ["gestionCompte"],
        "experimentationList" => ["consult"],
        "experimentationChange" => ["gestionCompte"],
        "experimentationWrite" => ["gestionCompte"],
        "experimentationDelete" => ["gestionCompte"],
        "piecetypeList" => ["consult"],
        "piecetypeChange" => ["gestionCompte"],
        "piecetypeWrite" => ["gestionCompte"],
        "piecetypeDelete" => ["gestionCompte"],
        "photolectureDisplay" => ["lecture"],
        "photolectureChange" => ["lecture"],
        "photolectureWrite" => ["lecture"],
        "photolectureDelete" => ["manage", "lecture"],
        "photolectureList" => ["lecture"],
        "photolectureExport" => ["manage"],
        "photolectureSwap" => ["lecture"],
        "especeList" => ["consult"],
        "especeChange" => ["manage"],
        "especeWrite" => ["manage"],
        "especeDelete" => ["manage"],
        "especeSearchAjax" => ["manage"],
        "importChange" => ["manage"],
        "importControl" => ["manage"],
        "importImport" => ["manage"],
        "metadatatypeList" => ["consult"],
        "metadatatypeChange" => ["gestionCompte"],
        "metadatatypeWrite" => ["gestionCompte"],
        "metadatatypeDelete" => ["gestionCompte"],
        "metadatatypeCopy" => ["gestionCompte"],
        "metadatatypeGetschema" => ["gestionCompte"],
        "metadatatypeIsarray" => ["gestionCompte"],
        "metadatatypeExport" => ["consult"],
        "metadatatypeImport" => ["gestionCompte"],
        "piecemetadataChange" => ["manage"],
        "piecemetadataWrite" => ["manage"],
        "piecemetadataDelete" => ["manage"],
        "piecemetadataImport" => ["manage"],
        "piecemetadataDisplay" => ["manage"],
        "piecemetadataExport" => ["manage"],
    ];
}
